# Generate with: code --list-extensions | xargs -L 1 echo code --install-extension
code --install-extension adrianwilczynski.alpine-js-intellisense
code --install-extension biomejs.biome
code --install-extension cardinal90.multi-cursor-case-preserve
code --install-extension christian-kohler.path-intellisense
code --install-extension daniloperes.relative-path-navigation
code --install-extension dannyconnell.split-html-attributes
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension ecmel.vscode-html-css
code --install-extension gencer.html-slim-scss-css-class-completion
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension golang.go
code --install-extension jhhtaylor.tabstronaut
code --install-extension jinliming2.vscode-go-template
code --install-extension jock.svg
code --install-extension kevinrose.vsc-python-indent
code --install-extension ko-dev.vscode-open-files-in-directory
code --install-extension lucax88x.codeacejumper
code --install-extension mblode.twig-language-2
code --install-extension metaseed.metago
code --install-extension metaseed.metajump
code --install-extension metaseed.metaword
code --install-extension ms-playwright.playwright
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension otovo-oss.htmx-tags
code --install-extension redhat.java
code --install-extension sankethdev.vscode-proto
code --install-extension sleistner.vscode-fileutils
code --install-extension sperovita.alpinejs-syntax-highlight
code --install-extension spryinno.kanpilot
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension uctakeoff.vscode-counter
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vue.volar
code --install-extension vunguyentuan.vscode-css-variables
code --install-extension waderyan.gitblame
code --install-extension wenfangdu.snippet-generator
code --install-extension wix.vscode-import-cost
code --install-extension zobo.php-intellisense
code --install-extension zxh404.vscode-proto3
code --install-extension ./custom-extensions/focus-by-index-0.0.2.vsix
